name: Deploy (Local)
on: 
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      - name: Deploy (Local)
        uses: appleboy/ssh-action@master

        with:
          host: ${{ secrets.USER }}
          password: ${{ secrets.PASS}}
          run: |
            set -e
            cd /home/lucci/Escritorio/mi_examen
            git pull