name: Deploy (Local)
on: 
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      - name: ${{ secrets.NAME }}
        shell: bash

        run: |
          set -e
          cd /home/lucci/Escritorio/mi_examen
          git pull