name: Deploy (Local)
on: 
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      - name: Deploy (Local)
        uses: appleboy/ssh-action@master

        with:
          host: ${{ secrets.HOST2 }}
          port: ${{ secrets.PORT2 }}
          password: ${{ secrets.PASS}}
          
          script: |
            set -e
            cd /home/lucci/Escritorio/mi_examen
            git pull